# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0003_auto_20170826_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='pub_time',
        ),
    ]
