# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:17
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0006_auto_20170827_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6807\u9898')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6807\u7b7e')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6b63\u6587')),
            ],
            options={
                'ordering': ['-update_time'],
                'verbose_name': '\u4e66\u520a\u8bc4\u8bba',
                'verbose_name_plural': '\u4e66\u520a\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6807\u9898')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6807\u7b7e')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6b63\u6587')),
            ],
            options={
                'ordering': ['-update_time'],
                'verbose_name': '\u6742\u6587',
                'verbose_name_plural': '\u6742\u6587',
            },
        ),
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6807\u9898')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6807\u7b7e')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6b63\u6587')),
            ],
            options={
                'ordering': ['-update_time'],
                'verbose_name': '\u5f71\u89c6\u8bc4\u8bba',
                'verbose_name_plural': '\u5f71\u89c6\u8bc4\u8bba',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_time'], 'verbose_name': '\u6280\u672f\u7c7b\u535a\u5ba2', 'verbose_name_plural': '\u6280\u672f\u7c7b\u535a\u5ba2'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('web', 'Web\u5f00\u53d1'), ('linux', '\u7cfb\u7edf\u8fd0\u7ef4'), ('algorithm', '\u7b97\u6cd5'), ('language', '\u7f16\u7a0b\u8bed\u8a00'), ('others', '\u5176\u4ed6')], default='web', max_length=64, verbose_name='\u7c7b\u522b'),
        ),
    ]
