# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0007_auto_20170828_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u4e66\u520a\u8bc4\u8bba', 'verbose_name_plural': '\u4e66\u520a\u8bc4\u8bba'},
        ),
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u6742\u6587', 'verbose_name_plural': '\u6742\u6587'},
        ),
        migrations.AlterModelOptions(
            name='filmreview',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u5f71\u89c6\u8bc4\u8bba', 'verbose_name_plural': '\u5f71\u89c6\u8bc4\u8bba'},
        ),
    ]
