# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0008_auto_20170830_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('content', models.TextField()),
                ('root_id', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Commits',
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='\u6458\u8981'),
        ),
        migrations.AddField(
            model_name='comment',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogadmin.Article'),
        ),
    ]
