# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0009_auto_20170906_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u6b63\u6587'),
        ),
    ]
