# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0010_auto_20170906_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_times',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
    ]
