# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0011_article_view_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6807\u7b7e'),
        ),
    ]
