# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0012_auto_20170906_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='view_times',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
        migrations.AddField(
            model_name='essay',
            name='view_times',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
        migrations.AddField(
            model_name='filmreview',
            name='view_times',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='filmreview',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6807\u7b7e'),
        ),
    ]
